### ISSUE TITLE
TypeError: Coda is not a constructor

### ISSUE THREAD

**Issue by muhajirdev** [parker-codes/coda-js#1]
Hey, I am following the code example 
```
const Coda = require('coda-js');

const coda = new Coda('**********-********-*********'); // insert your token

// trick for using async in a script
(async () => {

    const whoAmI = await coda.whoAmI();
    console.log(whoAmI);

})().catch(error => console.log(error));

```

I trie it on nodejs . So I use `require` instead of `import`

I got this 

```
TypeError: Coda is not a constructor
```

Thanks for making this btw

**Comment by parker-codes** [comment]
@muhajirframe Thanks for reaching out. To use this syntax, you must be running a Node environment that allows you to import modules. There is a difference between `require()` and `import` and they aren't interchangeable.

In this case, I recommend running `console.log(Coda)` right under where you require it. It will probably show you an object with one of the properties being `default`. If that is the case you might try `const Coda = require('coda-js').default;` to get the default package. Honestly, I don't work with CommonJS much, so if you can't figure it out I may need to change some things. 

If you want to try out modules, I recommend looking at [ParcelJS](https://parceljs.org/). You can specify ` --target node` when you run it to allow you to use imports. You can also add a `.babelrc` file and specify that you want to use @plugin-transform-runtime with corejs set to 2 for other newer features. Again, these are all optional. My examples are using this setup, so you will need to know how to use regular promises and require if you aren't using some of the newer JavaScript features. 👍

**Comment by muhajirdev** [comment]
Ohh, I see.

Thanks.

**Comment by parker-codes** [comment]
If you're not using imports, then get the package with:
```js
const Coda = require('coda-js').default;
```

Ift you also do not have async/await:
```js
coda.listDocs().then(function(docs) {
    console.log(docs);
});
```

**Comment by parker-codes** [comment]
@muhajirdev I've updated the package and it now works for CommonJS as well as ESModules.

So you can do either:

```js
const Coda = require('coda-js');
```

or:

```js
import Coda from 'coda-js';
```

**Comment by gadgetsan** [comment]
for some reason, i had to use `const Coda = require("coda-js").Coda;` to make it work...

**Comment by parker-codes** [comment]
@gadgetsan The package reached a new version recently. The main `Coda` constructor is not the top level export anymore. It is a named export.

If you are using Common JS, try `const { Coda } = require("coda-js");` to destructure it.
