### ISSUE TITLE
414 response on POST

### ISSUE THREAD

**Issue by mjoyce** [parker-codes/coda-js#2]
Requests are being sent with both `data` and `params` props, regardless of request method. On a `POST` (or any method that should send `data` instead of `params`) this will result in a [414 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414) when a large enough payload ends up in the url.

```
async request(url, params = {}, method = 'GET') {
  try {
    return await axios({ method, url, data: params, params });
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by parker-codes** [comment]
@mjoyce You are absolutely correct. Is this something you want to patch?
