### ISSUE TITLE
Getting the row ID after inserting an item to the row

### ISSUE THREAD

**Issue by fdwilogo** [parker-codes/coda-js#29]
Hi,

Is there a way to get the row ID after inserting an item to the row?

All i get back after inserting a row is just a mutate request id

as per the [Coda's documentation](https://coda.io/developers/apis/v1#tag/Rows/operation/upsertRows), it's possible.

**Comment by parker-codes** [comment]
You are right that it is now possible! The API must have been updated in the last couple of years to allow this.

Are you up for creating a PR to return both values instead of just the pending update?

**Comment by jschlight** [comment]
I've got this fixed on a fork that I can turn into a PR at any time. It's a trivial change.

I'm not able to run the Jest tests as they appear to be tied to a specific Coda API token. Maybe you've run into this before? Any suggestions?

**Comment by parker-crabnebula** [comment]
> I've got this fixed on a fork that I can turn into a PR at any time. It's a trivial change.
> 
> I'm not able to run the Jest tests as they appear to be tied to a specific Coda API token. Maybe you've run into this before? Any suggestions?

Yeah, I should have done a better job with those tests so let's ignore them for now. If you create the PR I can better visualize what changed to know what type of semver bump it is and we'll go from there. Thank you. 🙂

**Comment by parker-codes** [comment]
Whoops, commented with my work account, haha.

**Comment by parker-codes** [comment]
As you can see the PR has been merged, but the GitHub Actions workflow is having issues. I'll try a few more things and then I may need to publish locally.

**Comment by parker-codes** [comment]
Finally got it all working - let me know if you have any issues with version `4.1.2`!

**Comment by parker-codes** [comment]
Thanks @jschlight for the PR. :)

**Comment by jschlight** [comment]
I'm happy to have been able to contribute. The published package `4.1.2` appears to be working correctly.
