### ISSUE TITLE
Cannot find module '@babel/runtime-corejs2/helpers/objectSpread'

### ISSUE THREAD

**Issue by anthonysapien** [parker-codes/coda-js#4]
Hi, I'm trying to run coda-js within a create-react-app project and am running into this error:

Uncaught Error: Cannot find module '@babel/runtime-corejs2/helpers/objectSpread'
    at webpackEmptyContext (dist sync:2)
    at f (index.js:14)
    at p (index.js:29)
    at Object.push../node_modules/coda-js/dist/index.js.parcelRequire.Focm../API (index.js:457)
    at f (index.js:23)
    at push../node_modules/coda-js/dist/index.js.parcelRequire.JLF3 (index.js:42)
    at Object../node_modules/coda-js/dist/index.js (index.js:56)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Module../src/Finances/Finances.js (App.js:34)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Module../src/App.js (index.css:4)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Module../src/index.js (index.css?e32c:37)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.0 (serviceWorker.js:135)
    at __webpack_require__ (bootstrap:785)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

**Comment by parker-codes** [comment]
Hey @anthonysapien,

As the error explains, this package requires the object spread operator to be installed with babel/runtime-corejs. https://babeljs.io/docs/en/next/babel-runtime-corejs2.html

I'm sure there might be a way to package this so that it does not need extra modules to run, but I do not know how.

**Comment by anthonysapien** [comment]
Hi @google-mac, thanks for your response. I'm just getting back to looking into this. I'm using create-react-app 3.1.1, and it has a dependency on eslint 6. I think that's causing the issue. Something seems to have changed that makes the runtime objectSpread import invalid. I'm not expert in npm dependencies, but I thought it would be good for you to know as create-react-app is heavily used. Thanks for your help.

webpackEmptyContext
node_modules/coda-js/dist sync:2
f
node_modules/coda-js/dist/index.js:14
p
node_modules/coda-js/dist/index.js:29
push../node_modules/coda-js/dist/index.js.parcelRequire.Focm../API
node_modules/coda-js/dist/index.js:457
f
node_modules/coda-js/dist/index.js:23
push../node_modules/coda-js/dist/index.js.parcelRequire.JLF3
node_modules/coda-js/dist/index.js:42
./node_modules/coda-js/dist/index.js
node_modules/coda-js/dist/index.js:56

**Comment by anthonysapien** [comment]
Hi, can someone please help with this?
`npx create-react-app test`
`import Coda from 'coda-js';`
`Error: Cannot find module '@babel/runtime-corejs2/helpers/objectSpread'`

**Comment by parker-codes** [comment]
@anthonysapien I'm assuming that the babel package is no longer available or perhaps it needs to be specifically added via npm/yarn.

**Comment by anthonysapien** [comment]
@google-mac I tried to use coda-js again on a new create-react-app project and am running into the same issue as before.

I ran this:
`npm install --save @babel/runtime-corejs2`

The error is the same. I appreciate any help.

**Comment by anthonysapien** [comment]
The plot thickens. It doesn't actually seem to be caused by Babel. I tried to insert another arbitrary package, and it failed as well. The issue is with importing any package.

**Comment by parker-codes** [comment]
I've thought about rewriting this and compiling it down to use no dependencies. I think that would solve this class of issues. The problem is finding the time to do so.

**Comment by parker-codes** [comment]
@anthonysapien Thanks for your patience and your gentle prodding. I took the plunge this morning and refactored to TypeScript (for maintenance) and switched to [microbundle](https://www.npmjs.com/package/microbundle) instead of Parcel to remove the need for co-dependencies. I believe it should work with CommonJS, but it's geared for ES Modules. The API has not changed at all.

It is taking a while to update in the NPM registry, but check back when you'd like to see if it's ready at v2.

**Comment by anthonysapien** [comment]
Thanks so much, Parker. I’ll give it a try soon and let you know!

**Comment by anthonysapien** [comment]
It worked like a charm. Thank you for writing this and for the update!!
